#!/usr/bin/env bash

OS="7"
CMDLINE_ARGS=""
# prepare command line arguments for evaluation
#for arg in "$@"; do
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
	-os|--operating-system)
	    OS="$2"
	    shift # past argument
	    shift # past value
	    ;;
	*)
	    CMDLINE_ARGS="${CMDLINE_ARGS} $1"
	    shift # past argument
	    ;;
    esac
done
# echo $CMDLINE_ARGS

#if OS is neither 7 nor 9 give an error
if [[ "$OS" == "7" ]]; then
    echo "Attempt to run '${CMDLINE_ARGS}' in CentOS7 container."
    singularity run -e --bind /cvmfs/oasis.opensciencegrid.org/gluex/group/halld:/group/halld /cvmfs/singularity.opensciencegrid.org/jeffersonlab/gluex_prod:v1 ${HD_SINGULARITY}/gluex_install/gxrun/gluexrunscript.sh $CMDLINE_ARGS
elif [[ "$OS" == "9" ]]; then
    echo "Attempt to run '${CMDLINE_ARGS}' in alma9 container."
    singularity run -e --bind /cvmfs/oasis.opensciencegrid.org/gluex/group/halld:/group/halld /cvmfs/singularity.opensciencegrid.org/jeffersonlab/gluex_almalinux_9:latest ${HD_SINGULARITY}/gluex_install/gxrun/gluexrunscript.sh $CMDLINE_ARGS
else
    echo "Error: Unsupported operating system version requested. Only Centos7 (7) and alma9 (9) are supported."
    exit 1
fi


exit 0
